server:
  port: 9000


spring:
  h2:
    console.enabled: true
  jpa.database-platform: org.hibernate.dialect.H2Dialect
  mvc:
    log-request-details: true
    log-resolved-exception: true
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    username: sa
    password: password
    url: jdbc:h2:./auth
#    url: jdbc:postgresql://localhost:5432/app


logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: INFO
