spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  jpa.database-platform: org.hibernate.dialect.H2Dialect
  mvc:
    log-request-details: true
    log-resolved-exception: true
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: INFO

server:
  port: 8083