server:
  port: 9000

spring:
  datasource:
    url: jdbc:h2:~/test;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  jpa.database-platform: org.hibernate.dialect.H2Dialect
  mvc:
    log-request-details: true
    log-resolved-exception: true
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: INFO
